export enum EVENTS {
    RESIZE_APP = "RESIZE_APP",
    RESIZE = "RESIZE",
    KEY_PRESS = "KEY_PRESS",
    CHANGE_STAGE = "CHANGE_STAGE",
    RELOAD_STAGE = "RELOAD_STAGE",
    PAUSE = "PAUSE",
    UNPAUSE = "UNPAUSE",
    GAME_OVER = "GAME_OVER",
    GAME_WON = "GAME_WON"
}
  